"""Initial database structure

Revision ID: 9b50d06bdeb9
Revises: 
Create Date: 2024-11-11 17:00:25.304252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b50d06bdeb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objetos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('x_min', sa.Float(precision=3), nullable=True),
    sa.Column('y_min', sa.Float(precision=3), nullable=True),
    sa.Column('x_max', sa.Float(precision=3), nullable=True),
    sa.Column('y_max', sa.Float(precision=3), nullable=True),
    sa.Column('fecha_deteccion', sa.DateTime(), nullable=True),
    sa.Column('imagen_referencia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objetos')
    # ### end Alembic commands ###
